-- Emit ~/.config/hypr/nett-shell.conf from the merged config and the keybind table.
--
-- Everything the shell needs Hyprland to know lives in one generated file, sourced
-- once from hyprland.conf. Three things go in it:
--
--   binds        keys Hyprland does not already handle, dispatching to
--                GlobalShortcut (fast, no process spawn, survives key repeat)
--   appearance   border colour and gaps derived from the same theme values the
--                shell renders with, so window chrome cannot drift from the frame
--   layerrules   blur/alpha rules matched on the shell's own layer namespaces
--
-- The output is byte-stable for a given config: keys are sorted and nothing
-- timestamps itself. compile.lua hashes the result and only rewrites when it
-- actually changed, because regenerating means `hyprctl reload`, which re-applies
-- monitors and can visibly flash or reset scaling. A timestamp in the header would
-- defeat that entirely.

local hyprbinds = require("hyprbinds")

local hyprgen = {}

local HEADER = [[
# =============================================================================
#  GENERATED BY nett-shell -- DO NOT EDIT
# =============================================================================
#  Source of truth:
#    keys        ~/.config/quickshell/nett-shell/config/keybinds.lua
#    appearance  ~/.config/quickshell/nett-shell/config/config.lua
#
#  Regenerate with:  nettctl binds     (or just save config.lua)
#
#  This file is sourced AFTER bindings.conf, so a bind here would override one
#  there. The generator refuses to emit any key already bound in your config --
#  conflicts are reported instead, never silently resolved.
# =============================================================================
]]

--- Derive a GlobalShortcut name from an entry. Stable, lowercase, hyphenated.
function hyprgen.shortcut_name(entry)
  if entry.name and entry.name ~= "" then return entry.name end
  local parts = { tostring(entry.action) }
  if entry.arg ~= nil then
    local a = tostring(entry.arg)
    -- Numeric args become up/down so the name reads as an action, not a value.
    if type(entry.arg) == "number" then
      a = entry.arg >= 0 and "up" or "down"
    end
    parts[#parts + 1] = a
  end
  local name = table.concat(parts, "-")
  name = name:lower():gsub("[^%w%-]+", "-"):gsub("%-+", "-"):gsub("^%-", ""):gsub("%-$", "")
  return name
end

-- "bind" plus the flag letters Hyprland expects, in the order the existing
-- config already uses (e, then l, then d).
local function bind_keyword(entry)
  local flags = ""
  if entry.repeatable then flags = flags .. "e" end
  if entry.locked then flags = flags .. "l" end
  flags = flags .. "d"                      -- always emit descriptions
  return "bind" .. flags
end

local function split_key(spec)
  -- "SUPER SHIFT, S" -> "SUPER SHIFT", "S";  ", PRINT" -> "", "PRINT"
  local mods, key = tostring(spec):match("^([^,]*),%s*(.+)$")
  if not key then return nil, nil end
  return (mods:gsub("^%s+", ""):gsub("%s+$", "")), (key:gsub("^%s+", ""):gsub("%s+$", ""))
end

local function hex6(colour, fallback)
  local c = tostring(colour or ""):gsub("^#", "")
  if not c:match("^%x%x%x%x%x%x$") then return fallback end
  return c:lower()
end

--- Build the file contents.
--- @param cfg table   merged config
--- @param binds table keybind entries
--- @param taken table normalised id -> info, from hyprbinds.collect
--- @return string content, table conflicts, table emitted
function hyprgen.render(cfg, binds, taken)
  local hy = cfg.hyprland or {}
  local appid = hy.shortcutAppId or "nett"
  local out = { HEADER }
  local conflicts, emitted = {}, {}

  -- ---------------------------------------------------------------- keybinds
  if hy.emitBinds ~= false then
    local lines = {}

    for _, entry in ipairs(binds) do
      local mods, key = split_key(entry.key)
      if not key then
        conflicts[#conflicts + 1] = {
          key = tostring(entry.key), reason = "malformed key spec (expected \"MODS, KEY\")",
        }
      else
        local id = hyprbinds.normalise(mods, key)
        local clash = taken[id]
        if clash then
          conflicts[#conflicts + 1] = {
            key = entry.key,
            reason = ("already bound in %s"):format(clash.file),
            desc = entry.desc,
          }
        else
          local desc = (entry.desc or ""):gsub(",", " ")   -- commas break field parsing
          local dispatch
          if entry.action == "exec" then
            dispatch = "exec, " .. tostring(entry.exec or "")
          else
            dispatch = ("global, %s:%s"):format(appid, hyprgen.shortcut_name(entry))
          end
          lines[#lines + 1] = {
            id = id,
            text = ("%s = %s, %s, %s, %s"):format(
              bind_keyword(entry), mods, key, desc, dispatch),
          }
          emitted[#emitted + 1] = {
            key = entry.key,
            name = entry.action == "exec" and "(exec)" or hyprgen.shortcut_name(entry),
            desc = entry.desc,
            -- Carried through so compile.lua can also emit a `keybinds` array
            -- into config.json: Shortcuts.qml needs one GlobalShortcut per
            -- non-exec entry, using this SAME name, or Hyprland's `global,
            -- appid:name` dispatch would call a shortcut nothing registered.
            isExec = entry.action == "exec",
            action = entry.action,
            arg = entry.arg,
            repeatable = entry.repeatable and true or false,
            locked = entry.locked and true or false,
          }
        end
      end
    end

    -- Sort for byte-stable output.
    table.sort(lines, function(a, b) return a.id < b.id end)

    out[#out + 1] = "\n# --- keybinds ------------------------------------------------------------"
    if #lines == 0 then
      out[#out + 1] = "# (none)"
    else
      for _, l in ipairs(lines) do out[#out + 1] = l.text end
    end

    if #conflicts > 0 then
      out[#out + 1] = "\n# --- SKIPPED (already bound in your config) ------------------------------"
      local notes = {}
      for _, c in ipairs(conflicts) do
        notes[#notes + 1] = ("#   %-28s %s"):format(c.key, c.reason)
      end
      table.sort(notes)
      for _, n in ipairs(notes) do out[#out + 1] = n end
      out[#out + 1] = "#   Rename these in keybinds.lua, or remove the existing bind first."
    end
  end

  -- -------------------------------------------------------------- appearance
  local general = {}
  if hy.emitColors ~= false then
    local theme = cfg.theme or {}
    local active = hex6(hy.activeBorder ~= "" and hy.activeBorder or theme.accent, "cc0000")
    local inactive = hex6(hy.inactiveBorder, "2a1e20")
    general[#general + 1] = ("    col.active_border = rgba(%s%s)")
      :format(active, hy.activeBorderAlpha or "ee")
    general[#general + 1] = ("    col.inactive_border = rgba(%s%s)")
      :format(inactive, hy.inactiveBorderAlpha or "ff")
  end
  if hy.emitGaps ~= false then
    -- The frame's rounded corners and the window inset have to agree, or the
    -- corners clip windows. One number, emitted from the shell's own config.
    general[#general + 1] = ("    gaps_in = %d"):format(math.floor(hy.gapsIn or 5))
    general[#general + 1] = ("    gaps_out = %d"):format(math.floor(hy.gapsOut or 12))
  end
  if #general > 0 then
    out[#out + 1] = "\n# --- appearance (derived from the shell theme) ---------------------------"
    out[#out + 1] = "general {"
    for _, l in ipairs(general) do out[#out + 1] = l end
    out[#out + 1] = "}"
  end

  -- ------------------------------------------------------------- layer rules
  if hy.emitLayerRules ~= false then
    out[#out + 1] = "\n# --- layer rules --------------------------------------------------------"
    local blur = (cfg.theme or {}).blur and true or false
    if blur then
      -- Compositor blur behind the shell's surfaces. ignorealpha keeps the fully
      -- transparent parts of a layer from being blurred into a grey haze.
      for _, ns in ipairs({ "nett-bar", "nett-popup", "nett-osd", "nett-notifications",
                            "nett-launcher", "nett-control", "nett-dashboard" }) do
        out[#out + 1] = ("layerrule = blur, %s"):format(ns)
        out[#out + 1] = ("layerrule = ignorealpha 0.1, %s"):format(ns)
      end
    else
      out[#out + 1] = "# blur disabled (theme.blur = false)"
    end
    -- The frame overlay must never be blurred or dimmed: it is click-through
    -- chrome drawn over windows, and blurring it would smear the desktop.
    out[#out + 1] = "layerrule = noanim, nett-frame"
  end

  out[#out + 1] = ""
  return table.concat(out, "\n"), conflicts, emitted
end

return hyprgen
